# -*- mode: ruby -*-
# vi: set ft=ruby :

# Require the AWS provider plugin
require 'vagrant-aws'

# Create and configure the AWS instance(s)
Vagrant.configure('2') do |config|

  # Use dummy AWS box
  config.vm.box = 'aws-dummy'

  #config.aws_credentials.profile = "default"

  # Specify AWS provider configuration
  config.vm.provider 'aws' do |aws, override|
    aws.aws_dir = "C:/Users/h1dde/.aws"
    #aws.aws_profile = "default"

    # Read AWS authentication information from environment variables
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    # Specify SSH keypair to use
    aws.keypair_name = 'irrigation'

    # Specify region, AMI ID, and security group(s)
    aws.region = 'us-east-2'
    aws.ami = 'ami-0c55b159cbfafe1f0'
	  aws.instance_type = 't3.medium'
    aws.security_groups = [ 'vagrant-demo' ]

    aws.tags = {
      'Name' => 'Vagrant-Demo',
      'type' => 'mean'
    }

    aws.instance_ready_timeout = 30

    # Specify username and private key path
    override.ssh.username = 'ubuntu'
    override.ssh.private_key_path = 'C:/Users/h1dde/.ssh/irrigation.pem'
  end

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update -y
	  apt-get upgrade -y
  SHELL
end
